/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero;

import javax.swing.JOptionPane;
public class Deposito extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Deposito.class.getName());

    /**
     * Creates new form Deposito
     */
    public Deposito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        btndepositar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 0));
        jLabel2.setText("DEPOSITAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 220, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Monto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 110, 30));
        getContentPane().add(txtmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 180, 60));

        btndepositar.setBackground(new java.awt.Color(0, 204, 204));
        btndepositar.setFont(new java.awt.Font("Segoe UI Variable", 3, 14)); // NOI18N
        btndepositar.setForeground(new java.awt.Color(0, 0, 0));
        btndepositar.setText("DEPOSITAR");
        btndepositar.addActionListener(this::btndepositarActionPerformed);
        getContentPane().add(btndepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 170, 100));

        btnvolver.setBackground(new java.awt.Color(255, 0, 0));
        btnvolver.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(255, 255, 0));
        btnvolver.setText("VOLVER");
        btnvolver.addActionListener(this::btnvolverActionPerformed);
        getContentPane().add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 170, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositarActionPerformed
        // depositar 
        try {
    double monto = Double.parseDouble(txtmonto.getText());

    if (Login.clienteActual.depositar(monto)) {

        JOptionPane.showMessageDialog(
            this,
            "Depósito realizado correctamente.\n"
            + "Nuevo saldo: S/. "
            + String.format("%.2f", Login.clienteActual.getSaldo())
        );

        txtmonto.setText("");

    } else {

        JOptionPane.showMessageDialog(
            this,
            "El monto debe ser mayor que 0."
        );
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
        this,
        "Ingrese un monto válido."
    );
}
    }//GEN-LAST:event_btndepositarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
menu.setVisible(true);
this.dispose();
        
    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Deposito().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndepositar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtmonto;
    // End of variables declaration//GEN-END:variables
}
