/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero;

import javax.swing.JOptionPane;

/**
 *
 * @author effio
 */
public class Login extends javax.swing.JFrame {
    private int intentos = 0;
    public static Persona clienteActual;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcuenta = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btningresar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Perú Bank - Cajero Automático");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Stencil", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("   NUEVO PERÚ BANK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 270, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("USUARIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("CONTRASEÑA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, 50));
        getContentPane().add(txtcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, -1));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 130, -1));

        btningresar.setBackground(new java.awt.Color(51, 204, 0));
        btningresar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btningresar.setForeground(new java.awt.Color(0, 0, 0));
        btningresar.setText("INGRESAR");
        btningresar.addActionListener(this::btningresarActionPerformed);
        getContentPane().add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        btnsalir.setBackground(new java.awt.Color(255, 0, 51));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(this::btnsalirActionPerformed);
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero/USER.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 350, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // boton de ingresar al usuaroio 
        
        // Obtener usuario y contraseña
    String cuenta = txtcuenta.getText();
    String contraseña = new String(txtpassword.getPassword());

    // Buscar el usuario en la matriz
    String[] datosCuenta = DatosCajero.buscarCuentaEnMatriz(cuenta);

    if (datosCuenta != null && contraseña.equals("123456")) {

        // Crear el cliente usando los datos de la matriz
        clienteActual = new Persona(
            datosCuenta[1], // nombre
            datosCuenta[0], // usuario
            contraseña,     // contraseña
            Double.parseDouble(datosCuenta[2]) // saldo
        );

        // Guardar la persona en el ArrayList
        DatosCajero.agregarPersona(clienteActual);

        JOptionPane.showMessageDialog(
            this,
            "Bienvenido al Nuevo Perú Bank"
        );

        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();

    } else {

        // Aumentar el número de intentos
        intentos++;

        if (intentos >= 3) {

            JOptionPane.showMessageDialog(
                this,
                "Ha superado los 3 intentos permitidos. El sistema finalizará."
            );

            System.exit(0);

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Usuario o contraseña incorrecta.\n"
                + "Intentos restantes: " + (3 - intentos)
            );
        }
    }
        

   
      
    }//GEN-LAST:event_btningresarActionPerformed
    
    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(
    this,
    "¿Está seguro de salir del sistema?",
    "Confirmar salida",
    JOptionPane.YES_NO_OPTION
);

if (respuesta == JOptionPane.YES_OPTION) {
    JOptionPane.showMessageDialog(
        this,
        "Gracias por utilizar Nuevo Perú Bank."
    );
    
    System.exit(0);
}
    }//GEN-LAST:event_btnsalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtcuenta;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
