/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero;

import javax.swing.JOptionPane;

/**
 *
 * @author effio
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btndepositar = new javax.swing.JButton();
        btnretirar = new javax.swing.JButton();
        btnsaldo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("NUEVO PERU BANK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 410, -1));

        btnsalir.setBackground(new java.awt.Color(204, 255, 255));
        btnsalir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 0, 0));
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(this::btnsalirActionPerformed);
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 140, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Bienvenido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 220, 30));

        btndepositar.setBackground(new java.awt.Color(204, 255, 255));
        btndepositar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btndepositar.setForeground(new java.awt.Color(0, 51, 153));
        btndepositar.setText("DEPOSITAR");
        btndepositar.addActionListener(this::btndepositarActionPerformed);
        getContentPane().add(btndepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 140, 80));

        btnretirar.setBackground(new java.awt.Color(204, 255, 255));
        btnretirar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnretirar.setForeground(new java.awt.Color(153, 153, 0));
        btnretirar.setText("RETIRAR");
        btnretirar.addActionListener(this::btnretirarActionPerformed);
        getContentPane().add(btnretirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, 80));

        btnsaldo.setBackground(new java.awt.Color(204, 255, 255));
        btnsaldo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnsaldo.setForeground(new java.awt.Color(153, 0, 153));
        btnsaldo.setText("CONSULTAR SALDO");
        btnsaldo.addActionListener(this::btnsaldoActionPerformed);
        getContentPane().add(btnsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 160, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositarActionPerformed
        // deposito 
        Deposito deposito = new Deposito();
deposito.setVisible(true);
this.dispose();
        
    }//GEN-LAST:event_btndepositarActionPerformed

    private void btnretirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretirarActionPerformed
        // retirar 
        Retiro retiro = new Retiro();
retiro.setVisible(true);
this.dispose();

    }//GEN-LAST:event_btnretirarActionPerformed

    private void btnsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaldoActionPerformed
        // consulta de de saldo 
        Saldo saldo = new Saldo();
saldo.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnsaldoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // salir 
        int respuesta = JOptionPane.showConfirmDialog(
    this,
    "¿Está seguro de salir del sistema?",
    "Confirmar salida",
    JOptionPane.YES_NO_OPTION
);

if (respuesta == JOptionPane.YES_OPTION) {
    JOptionPane.showMessageDialog(
        this,
        "Gracias por utilizar Nuevo Perú Bank."
    );
    
    System.exit(0);
}
        
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndepositar;
    private javax.swing.JButton btnretirar;
    private javax.swing.JButton btnsaldo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
